// Auto-generated by generate-manifest.ps1 — do not edit by hand.
// Re-run that script after adding/removing files in chirps/short or chirps/long.
const CHIRPS = {
  "short": [
    "File0038.mp3",
    "File0039.mp3",
    "File0040.mp3",
    "File0041.mp3",
    "File0042.mp3",
    "File0043.mp3",
    "File0044.mp3",
    "File0045.mp3",
    "File0046.mp3",
    "File0047.mp3",
    "File0048.mp3",
    "File0049.mp3"
  ],
  "long": [
    "File0050.mp3",
    "File0051.mp3",
    "File0052.mp3",
    "File0053.mp3",
    "File0054.mp3",
    "File0055.mp3",
    "File0056.mp3",
    "File0057.mp3",
    "File0060.mp3"
  ]
};
