<#
  Regenerates chirps-data.js by scanning chirps/short and chirps/long.
  Run this any time you add or remove audio files, then redeploy.

  Usage:  powershell -ExecutionPolicy Bypass -File generate-manifest.ps1
#>

$root = Split-Path -Parent $MyInvocation.MyCommand.Path
$shortDir = Join-Path $root "chirps\short"
$longDir  = Join-Path $root "chirps\long"

function Get-AudioFileNames($dir) {
    if (-not (Test-Path $dir)) { return @() }
    Get-ChildItem -Path $dir -File |
        Where-Object { $_.Extension -match '\.(mp3|wav|m4a|aac|ogg)$' } |
        Sort-Object Name |
        ForEach-Object { $_.Name }
}

$shortFiles = Get-AudioFileNames $shortDir
$longFiles  = Get-AudioFileNames $longDir

if ($shortFiles.Count -eq 0) { Write-Warning "No audio files found in chirps\short" }
if ($longFiles.Count -eq 0)  { Write-Warning "No audio files found in chirps\long" }

function Format-JsonArray($names) {
    if ($names.Count -eq 0) { return "[]" }
    $lines = $names | ForEach-Object { "    `"$_`"" }
    return "[`n" + ($lines -join ",`n") + "`n  ]"
}

$content = @"
// Auto-generated by generate-manifest.ps1 -- do not edit by hand.
// Re-run that script after adding/removing files in chirps/short or chirps/long.
const CHIRPS = {
  "short": $(Format-JsonArray $shortFiles),
  "long": $(Format-JsonArray $longFiles)
};
"@

Set-Content -Path (Join-Path $root "chirps-data.js") -Value $content -Encoding utf8

Write-Host "Wrote chirps-data.js with $($shortFiles.Count) short file(s) and $($longFiles.Count) long file(s)."
